// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/test" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/test": typeof import("./app/routes/test.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};